# Generated by Django 4.2.23 on 2025-08-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_form_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
